### ISSUE TITLE
Put [skip ci] at end of commit message

### ISSUE THREAD

**Issue by Veikkosuhonen** [HRemonen/CommitSense#4]
The keyword can be anywhere (not sure about commit message body?) in the msg https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/, maybe put it at the end so it doesn't clutter the conventional commits message format

**Comment by HRemonen** [comment]
Moved to the footer.

I was acually thinking about using the following syntax before I implemented this

> Alternatively, you can end the commit message with two empty lines followed by either:
> 
> skip-checks:true
> skip-checks: true

from the [docs](https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs), but that would have f*cked the co-authors as they both need to be last on the commit footer apparently in order to work.
